# Generated by Django 3.0 on 2020-07-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('wish_rrp', models.IntegerField(verbose_name='IRRP')),
                ('user_msg', models.TextField(verbose_name='Message')),
                ('post_date', models.DateTimeField(verbose_name='Post time')),
            ],
        ),
    ]
