# Generated by Django 3.0 on 2020-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail:'),
        ),
    ]
