# Generated by Django 3.0 on 2020-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_register_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='register',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Post time'),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.EmailField(default='', max_length=254, verbose_name='uemail'),
        ),
        migrations.AlterField(
            model_name='register',
            name='wish_rrp',
            field=models.IntegerField(verbose_name='rrp'),
        ),
    ]
